### ISSUE TITLE
TypeError: callback is not a function in index.js:153

### ISSUE THREAD

**Issue by melkir** [whitef0x0/node-email-verification#41]
I have the following error when I try to do the following code 

```
var config = require('./config');
// import our User mongoose model
var User        = require('../app/models/user');

module.exports = function (nev) {

    nev.configure({
        verificationURL: 'http://localhost:8080/verification/${URL}',
        persistentUserModel: User,
        tempUserCollection: 'tmp_users',

        transportOptions: {
            service: 'SendGrid',
            auth: {
                api_key: config.mailer.key
            }
        },
        verifyMailOptions: {
            from: 'Do not reply <no-reply@myapp.com>',
            subject: 'Please confirm account',
            html: 'Click the following link to confirm your account:</p><p>${URL}</p>',
            text: 'Please confirm your account by clicking the following link: ${URL}'
        }
    });

};
```

```
/home/melkir/WebstormProjects/appdatabase/node_modules/email-verification/index.js:153
    return callback(null, options);
           ^

TypeError: callback is not a function
    at Object.configure (/home/melkir/WebstormProjects/appdatabase/node_modules/email-verification/index.js:153:12)
    at module.exports (/home/melkir/WebstormProjects/appdatabase/config/mailer.js:7:9)
    at Object.<anonymous> (/home/melkir/WebstormProjects/appdatabase/server.js:27:27)

```
Do you know what can be the cause ?

**Comment by melkir** [comment]
I have replace return 

> callback(null, options)

by

> return options

The error is gone by I don't know if everything will work after that

**Comment by whitef0x0** [comment]
@melkir configure takes a callback

**Comment by whitef0x0** [comment]
Updated the README to reflect this.

**Comment by melkir** [comment]
Thank you !
