### ISSUE TITLE
Error sending confirmation mail: No recipients defined

### ISSUE THREAD

**Issue by Hanzofm** [whitef0x0/node-email-verification#60]
Hi, I'm using your library and works fine for me except on the confirmation mail:

When I try to confirm to user that their verification mail has been confirmed the console returns me this error
```

Error: No recipients defined
    at SMTPConnection._formatError (D:\WebStorm\Alertame-Backend\node_modules\smtp-connection\src\smtp-connection.js:384:15)
    at SMTPConnection._setEnvelope (D:\WebStorm\Alertame-Backend\node_modules\smtp-connection\src\smtp-connection.js:566:30)
    at SMTPConnection.send (D:\WebStorm\Alertame-Backend\node_modules\smtp-connection\src\smtp-connection.js:270:10)
    at sendMessage (D:\WebStorm\Alertame-Backend\node_modules\nodemailer-smtp-transport\src\smtp-transport.js:118:20)
    at D:\WebStorm\Alertame-Backend\node_modules\nodemailer-smtp-transport\src\smtp-transport.js:157:17
    at SMTPConnection._actionAUTHComplete (D:\WebStorm\Alertame-Backend\node_modules\smtp-connection\src\smtp-connection.js:8
82:5)
    at SMTPConnection.<anonymous> (D:\WebStorm\Alertame-Backend\node_modules\smtp-connection\src\smtp-connection.js:239:22)
    at SMTPConnection._processResponse (D:\WebStorm\Alertame-Backend\node_modules\smtp-connection\src\smtp-connection.js:516:
16)
    at SMTPConnection._onData (D:\WebStorm\Alertame-Backend\node_modules\smtp-connection\src\smtp-connection.js:353:10)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:543:20)

```

This is the mailOptions passed to `transporter.sendMail`

```
{ from: 'Do Not Reply <mymail@gmail.com>',
  subject: 'Successfully verified!',
  html: '<p>Your account has been successfully verified.</p>',
  text: 'Your account has been successfully verified.',
  to: 'mymail@gmail.com' }
```

What could be wrong? Thanks

**Comment by whitef0x0** [comment]
What version of Node and Mongo are you using?

**Comment by techaware** [comment]
I also faced the same issue. However, it looks like if option shouldSendConfirmation is True (default), then confirmTempUser API function assumes email field on the persistent User is named 'email'. 
`            if (options.shouldSendConfirmation) {
              sendConfirmationEmail(**savedUser.email**, null);
            }
            return callback(null, user);
          });`

Work around could be: set shouldSendConfirmation: false and then call sendConfirmationEmail with correct email field.

**Comment by whitef0x0** [comment]
@techaware @Hanzofm this has already been fixed on the master branch. I think I just forgot to update the npm package.

**Comment by Hanzofm** [comment]
Hi,

I've updated the npm package to `0.4.6` version and then the email is succesfully sended but, two times...

I've configured the `emailFieldName: 'mail'`

Is this normal?
