### ISSUE TITLE
[ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by daureslaurent** [whitef0x0/node-email-verification#78]
events.js:136
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at Object.randomBytes (internal/crypto/random.js:44:11)
    at Object.options.source (/home/lolo/izipadel/node_modules/rand-token/index.js:60:25)
    at Object.generate (/home/lolo/izipadel/node_modules/rand-token/index.js:95:29)
    at /home/lolo/izipadel/node_modules/email-verification/index.js:286:58
    at model.Query.<anonymous> (/home/lolo/izipadel/node_modules/mongoose/lib/model.js:4020:16)
    at /home/lolo/izipadel/node_modules/kareem/index.js:273:21
    at /home/lolo/izipadel/node_modules/kareem/index.js:131:16
    at process._tickCallback (internal/process/next_tick.js:150:11)

**Comment by hizaku2000** [comment]
I have the same issue with node v9.2. The error doesn't occur when using node v8.9.4. possibly the version of rand-token is not compatible with node v9

**Comment by engMaher** [comment]
by drilling down to node_modules/rand-token/index.js:60:25 , after interchanging the value given to the  switch case "default and crypto" , it works fine , but does this affect the predictability of the random tokens?

**Comment by joshbenz** [comment]
yeah i'm having this problem right now. rand-token says they fixed it but you have to update it.
https://github.com/sehrope/node-rand-token/issues/9
probably to 0.4.0 but this email-verification is using ^0.2.1

**Comment by SeunghunSunmoonLee** [comment]
maintainers, please update rand-token to 0.4 in the package.json !

**Comment by chiragmittal19** [comment]
OS: Windows 10 x64
node version: 10.2.1
rand-token version: 0.4.0

Still getting the same error!

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1276:14)
    at D:\Projects\learning_app\node-utils\json_file_generation.js:130:8
    at Query.<anonymous> (D:\Projects\learning_app\node-utils\query.js:25:16)
    at Query.handleReadyForQuery (D:\Projects\learning_app\node_modules\pg\lib\query.js:126:10)
    at Connection.<anonymous> (D:\Projects\learning_app\node_modules\pg\lib\client.js:163:19)
    at Connection.emit (events.js:182:13)
    at TLSSocket.<anonymous> (D:\Projects\learning_app\node_modules\pg\lib\connection.js:123:12)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)

**Comment by joshbenz** [comment]
@chiragmittal19 You are actually getting a different error that has to do with " Object.fs.writeFile" instead of "Object.randomBytes". I suspect your error isn't related to this package. Are you using fs.writeFile anywhere? It requires a callback as per the documentation, https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback

**Comment by riyazpanarwala** [comment]
The above error is resolved when rand token package gets updated to 0.4.0.
But i got below error while sending email using nev.sendVerificationEmail

{ Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1036:34)
    at TLSSocket.emit (events.js:159:13)
    at TLSSocket._finishInit (_tls_wrap.js:637:8) code: 'ECONNECTION', command:
'CONN' }

**Comment by riyazpanarwala** [comment]
To solve above error i have added below parameters in nev transportOptions config.
tls: {
  rejectUnauthorized: false
}

**Comment by riyazpanarwala** [comment]
Got this error while confirming user. This happens when tring to store temporary users into real users.

{ ValidationError: real_users validation failed
    at ValidationError.inspect (E:\wamp\www\node-email-verification-master\node-
email-verification-master\examples\express\node_modules\mongoose\lib\error\valid
ation.js:56:24)
    at formatValue (util.js:438:38)
    at inspect (util.js:328:10)
    at format (util.js:195:12)
    at Console.log (console.js:131:21)
    at E:\wamp\www\node-email-verification-master\node-email-verification-master
\examples\express\node_modules\email-verification\index.js:419:19
    at E:\wamp\www\node-email-verification-master\node-email-verification-master
\examples\express\node_modules\mongoose\lib\model.js:4422:16
    at $__save.error (E:\wamp\www\node-email-verification-master\node-email-veri
fication-master\examples\express\node_modules\mongoose\lib\model.js:379:16)
    at E:\wamp\www\node-email-verification-master\node-email-verification-master
\examples\express\node_modules\kareem\index.js:246:48
    at next (E:\wamp\www\node-email-verification-master\node-email-verification-
master\examples\express\node_modules\kareem\index.js:167:27)
    at Kareem.execPost (E:\wamp\www\node-email-verification-master\node-email-ve
rification-master\examples\express\node_modules\kareem\index.js:217:3)
    at _handleWrapError (E:\wamp\www\node-email-verification-master\node-email-v
erification-master\examples\express\node_modules\kareem\index.js:245:21)
    at E:\wamp\www\node-email-verification-master\node-email-verification-master
\examples\express\node_modules\kareem\index.js:272:14
    at _next (E:\wamp\www\node-email-verification-master\node-email-verification
-master\examples\express\node_modules\kareem\index.js:94:14)
    at process.nextTick (E:\wamp\www\node-email-verification-master\node-email-v
erification-master\examples\express\node_modules\kareem\index.js:452:38)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
  errors: {},
  _message: 'real_users validation failed',
  name: 'ValidationError' }

**Comment by joshbenz** [comment]
@riyazpanarwala  ah I see. I'm not really sure. I'm not a maintainer or anything, I just happened to know how to fix the bug for this issue, so I did lol. Your issue doesn't seem to be related to this bug and the issue is closed, so you might wanna open a new issue with your new problem.

**Comment by iamal12** [comment]
update to  latest version of npm,  just run the command
npm install npm@latest -g

**Comment by chiheon** [comment]
node.js : 10.9.0
rand-token : 0.4.0
I can solve this problem by change the code named "index.js" in "email-verification" 
( "email-verification" is located in node_modules ) 
please change the code 
>> var options = { ~~~}; and var transporter;   upto  "module.exports =  ~~~"

**Comment by Npradheepan** [comment]
PS C:\Users\pradh\OneDrive\Desktop\Node.js\Ex_5> node index.js
Node.js!
fs.js:169
  throw new ERR_INVALID_CALLBACK(cb);
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined      
    at maybeCallback (fs.js:169:9)
    at Object.appendFile (fs.js:1540:14)
    at Object.<anonymous> (C:\Users\pradh\OneDrive\Desktop\Node.js\Ex_5\index.js:3:4)  
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_CALLBACK'
}

**Comment by Npradheepan** [comment]
I have this problem please  help me.
